# https://hub.docker.com/r/bildcode/pyside2
FROM bildcode/pyside2

#FROM python:3.8.2
#
#RUN apt-get update --yes
#RUN apt-get upgrade --yes
#RUN apt-get install --yes \
#    x11-apps
#	x11-utils
#	x11-xserver-utils
#	dbus-x11
#	libxkbcommon-x11-0
#
#	eglfs linuxfb minimal minimalegl offscreen vnc wayland-egl wayland wayland-xcomposite-egl wayland-xcomposite-glx webgl xcb
#
#RUN pip install pyside2
#
#
#wget http://download.qt.io/official_releases/qt/5.12/5.12.9/qt-opensource-linux-x64-5.12.9.run
#chmod +x qt-opensource-linux-x64-5.12.9.run
#./qt-opensource-linux-x64-5.12.9.run
#
#apt-get install build-essential
#apt-get install libfontconfig1
#apt-get install mesa-common-dev -y
#apt-get install libglu1-mesa-dev -y